import fs from 'fs'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

// __dirname is client/ — ../certs/ points to the repo-root certs/ directory generated by mkcert.
const certDir = path.resolve(__dirname, '../certs')

export default defineConfig(({ command }) => ({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 5173,
    // Only read certs for the dev server — during vite build the certs directory doesn't exist.
    https: command === 'serve' ? {
      key: fs.readFileSync(path.join(certDir, 'localhost-key.pem')),
      cert: fs.readFileSync(path.join(certDir, 'localhost.pem')),
    } : undefined,
  },
}))
